### PR TITLE
Deleting test with deprecated constructor behavior

### PR DESCRIPTION
**Pull request by nscarcella**
I propose to delete this (and potentially more, but I'm specially interested in this) test case.

Since we are formally deprecating the use of constructors, I believe the sane thing to do is to remove test expectations about them. There is no point in requiring a Wollok implementation to sustain a construction we are dropping.

Maybe, as a thumbs rule, we can comment (or straight forward delete) tests of deprecated features. Eventually, if we include annotations (as I hope we will) we can mark the tests to be ignored and print separate results of deprecated features that don't break the CI tools.

What do you guys think?

### CODE REVIEW

**Comment by nscarcella** [comment]
relates to #5

**Comment by nscarcella** [comment]
Ok, so I start to think that maybe deleting the test might not be the best idea, but I would still like to be able to distinguish between deprecated and non-deprecated features here. Or, at least, to decide on the process we will follow to drop deprecated features and their tests so we can keep code clean.

**Comment by fdodino** [comment]
I agree that we shouldn't take care of deprecated constructions.
I'll also delete constructor tests as soon as we have the opportunity to remove constructors at all from the wollok-xtext implementation.

**Comment by nscarcella** [comment]
@fdodino @npasserini So, what do you guys think should be the general approach to this? Do we delete tests as soon as we deprecate a feature? The more I think about it, the more it feels like we should not delete the tests right away. Maybe we should have some way to mark them as deprecated so we can ignore them if we want to, but leave the tests until we formally remove support for the feature.

**Comment by fdodino** [comment]
For this case, I would just relax, because I don't want to migrate constructor sanity tests for the new Wollok language specification. For future cases, I'll se whenever it comes.

**Comment by npasserini** [comment]
Si tenemos funcionalidad y tests andando, yo no los borraría hasta que no
sea el momento de eliminar todo junto.
En este caso puntual, además, al borrar un test de constructor uno podría
hacer el ejercicio de validar que los tests de la nueva funcionalidad
cubran las situaciones análogas.

Pero, si vos no tenés andando constructores o si tenemos tests que dan
problemas, creo que hay que evitar ponerle laburo a cosas que estamos cerca
de eliminar. Entonces si hay que sacar los tests del camino para mí vale, a
lo mejor pensando en el párrafo anterior, es más sano comentarlo que
borrarlo, si te parece que vale la pena como guía para garantizar el
correcto testeo de la nueva funcionalidad.

**Comment by nscarcella** [comment]
Ok, en base a lo que hablamos, cambié de opinión. Este test pasa sin problemas en todas las implementaciones así que creo que no está bueno borralo hasta que formalmente eliminemos el soporte para constructores.

**Comment by npasserini** [comment]
Grosso.

**Pull request closed without merging**
